// frontend/src/components/CommandPreview.vue
<script setup>
import { ref } from 'vue'

const props = defineProps({
  steps: { type: Array, default: () => [] },
  err: { type: String, default: '' },
})

const open = ref(false)
const copied = ref(false)

async function copy() {
  const text = props.steps.join('\n')
  try {
    await navigator.clipboard.writeText(text)
    copied.value = true
    setTimeout(() => (copied.value = false), 1500)
  } catch {
    /* 剪贴板不可用时忽略 */
  }
}
</script>

<template>
  <div class="cmd">
    <button class="toggle ghost" @click="open = !open">
      <span class="caret" :class="{ open }">›</span>
      将执行的命令
      <span v-if="steps.length > 1" class="badge">{{ steps.length }} 步</span>
    </button>

    <div v-if="open" class="body">
      <div v-if="err" class="banner err">{{ err }}</div>

      <template v-else-if="steps.length">
        <div class="toolbar">
          <button class="tiny" @click="copy">{{ copied ? '已复制' : '复制' }}</button>
        </div>
        <pre v-for="(s, i) in steps" :key="i" class="line">{{ s }}</pre>
      </template>

      <div v-else class="empty-hint">参数填完整后这里会显示要执行的命令</div>
    </div>
  </div>
</template>

<style scoped>
.cmd {
  margin-top: 2px;
}

.toggle {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
}

.caret {
  display: inline-block;
  transition: transform 0.15s;
  font-size: 14px;
  line-height: 1;
}

.caret.open {
  transform: rotate(90deg);
}

.badge {
  font-size: 11px;
  padding: 0 6px;
  border-radius: 8px;
  background: #eef1f5;
  color: var(--text-dim);
}

.body {
  margin-top: 8px;
}

.toolbar {
  display: flex;
  justify-content: flex-end;
  margin-bottom: 6px;
}

.line {
  margin: 0 0 6px;
  padding: 9px 11px;
  background: #f7f8fa;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  font-size: 11.5px;
  line-height: 1.55;
  color: #334155;
  white-space: pre-wrap;
  word-break: break-all;
  user-select: text;
}
</style>

// frontend/src/components/CommandPreview.tsx
import { useState } from 'react';
import { Accordion, Button } from '@heroui/react';
import './CommandPreview.css';

interface CommandPreviewProps {
  steps: string[];
  err: string;
}

export default function CommandPreview({ steps, err }: CommandPreviewProps) {
  const [copied, setCopied] = useState(false);

  async function copy() {
    const text = steps.join('\n');
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      /* 剪贴板不可用时忽略 */
    }
  }

  return (
    <div className="cmd">
      <Accordion.Root className="cmd-root">
        <Accordion.Item id="cmd">
          <Accordion.Heading>
            <Accordion.Trigger className="toggle">
              <Accordion.Indicator>
                <span className="caret">›</span>
              </Accordion.Indicator>
              将执行的命令
              {steps.length > 1 && <span className="badge">{steps.length} 步</span>}
            </Accordion.Trigger>
          </Accordion.Heading>
          <Accordion.Panel className="u-coll-content">
            <div className="body">
              {err ? (
                <div className="banner err">{err}</div>
              ) : steps.length ? (
                <>
                  <div className="toolbar">
                    <Button size="sm" onPress={copy}>
                      {copied ? '已复制' : '复制'}
                    </Button>
                  </div>
                  {steps.map((s, i) => (
                    <pre key={i} className="line">
                      {s}
                    </pre>
                  ))}
                </>
              ) : (
                <div className="empty-hint">参数填完整后这里会显示要执行的命令</div>
              )}
            </div>
          </Accordion.Panel>
        </Accordion.Item>
      </Accordion.Root>
    </div>
  );
}
