// frontend/src/tabs/TrimTab.vue
<script setup>
import { ref, computed } from 'vue'
import FilePicker from '../components/FilePicker.vue'
import MediaInfoCard from '../components/MediaInfoCard.vue'
import VideoScrubber from '../components/VideoScrubber.vue'
import CommandPreview from '../components/CommandPreview.vue'
import ProgressPanel from '../components/ProgressPanel.vue'
import { api } from '../api'
import { useTask } from '../composables/useTask'
import { useMediaSource, useCommandPreview, baseFields } from '../composables/useTab'

const { file, info, loadingInfo, probeError, outPath, previewURL, previewNote, preparing, load } = useMediaSource('trim', {
  withPreview: true,
})

const accurate = ref(false)
const range = ref({ start: 0, end: 0 })

async function onFile(f) {
  await load(f)
  if (f && info.value) {
    range.value = { start: 0, end: info.value.duration || 0 }
  }
}

const segLen = computed(() => Math.max(0, (range.value.end || 0) - (range.value.start || 0)))

function buildSpec() {
  if (!file.value || !outPath.value || !info.value) return null
  if (!range.value.end) return null
  return {
    kind: 'trim',
    output: outPath.value,
    ...baseFields(file, info),
    trim: { start: Number(range.value.start), end: Number(range.value.end), accurate: accurate.value },
  }
}

const { cmd } = useCommandPreview(buildSpec, [file, outPath, accurate, range])
const { running, progress, stage, logs, result, start, cancel } = useTask()

async function run() {
  const spec = buildSpec()
  if (!spec) return
  try {
    await start(spec)
  } catch (e) {
    window.alert('无法启动任务：' + (e?.message || e))
  }
}

async function pickOutput() {
  const ext = file.value?.name?.match(/\.[^.]+$/)?.[0] || '.mp4'
  const name = (file.value?.name || 'output').replace(/\.[^.]+$/, '') + '_trimmed' + ext
  const p = await api.pickSaveFile(name, `*${ext}`)
  if (p) outPath.value = p
}

const modeHint = computed(() =>
  accurate.value
    ? '精确模式：逐帧定位，起点终点都准。速度取决于片段长度'
    : '快速模式：不重新编码，秒级完成。但起止点会吸附到最近的关键帧，可能差 1~2 秒'
)
</script>

<template>
  <div class="card">
    <h2>源文件</h2>
    <FilePicker :model-value="file" @update:model-value="onFile" label="选择要截取的视频，也可以直接拖进来" />
    <div v-if="file" style="margin-top: 12px">
      <MediaInfoCard :info="info" :loading="loadingInfo" />
      <div v-if="preparing" class="banner info" style="margin-top: 10px">正在准备预览…</div>
      <div v-else-if="previewNote" class="banner info" style="margin-top: 10px">{{ previewNote }}</div>
      <div v-if="probeError" class="banner warn" style="margin-top: 10px">{{ probeError }}</div>
    </div>
  </div>

  <div v-if="file && previewURL" class="card">
    <h2>选择片段 <span class="hint">拖动两端手柄调整范围，点上任意位置可跳到该处预览</span></h2>
    <VideoScrubber
      :src="previewURL"
      :duration="info?.duration || 0"
      mode="range"
      :model-value="range"
      @update:model-value="range = $event"
    />
  </div>

  <div v-if="file" class="card">
    <h2>截取方式</h2>
    <div class="modes">
      <button class="mode" :class="{ on: !accurate }" @click="accurate = false">
        <b>快速</b>
        <span>不重编码，秒级完成</span>
      </button>
      <button class="mode" :class="{ on: accurate }" @click="accurate = true">
        <b>精确</b>
        <span>逐帧精确，需要重新编码</span>
      </button>
    </div>
    <div class="banner info" style="margin-top: 12px; margin-bottom: 0">{{ modeHint }}</div>
  </div>

  <div v-if="file" class="card">
    <h2>输出</h2>
    <div class="field">
      <label>输出路径</label>
      <div class="row">
        <input v-model="outPath" type="text" class="mono" style="flex: 1" />
        <button @click="pickOutput">浏览…</button>
      </div>
    </div>

    <CommandPreview :steps="cmd.steps" :err="cmd.err" />

    <div class="row" style="margin-top: 14px">
      <button class="primary" :disabled="running || !outPath || segLen <= 0" @click="run">
        {{ running ? '处理中…' : `开始截取（${segLen.toFixed(1)} 秒）` }}
      </button>
    </div>
  </div>

  <ProgressPanel
    :running="running"
    :progress="progress"
    :stage="stage"
    :logs="logs"
    :result="result"
    @cancel="cancel"
    @open-file="api.openPath"
    @open-dir="api.openDirectory"
  />
</template>

<style scoped>
.modes {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 10px;
}

.mode {
  display: flex;
  flex-direction: column;
  gap: 3px;
  align-items: flex-start;
  text-align: left;
  padding: 11px 14px;
  border-radius: var(--radius-sm);
  background: #fbfcfd;
}

.mode b {
  font-size: 13px;
  font-weight: 500;
}

.mode span {
  font-size: 11.5px;
  color: var(--text-mute);
}

.mode.on {
  border-color: var(--primary);
  background: var(--primary-soft);
}

.mode.on b {
  color: var(--primary);
}

.mono {
  font-size: 12px;
}
</style>

// frontend/src/tabs/TrimTab.tsx
import { useEffect, useRef, useState } from 'react';
import { Input } from '@heroui/react';
import FilePicker from '../components/FilePicker';
import MediaInfoCard from '../components/MediaInfoCard';
import VideoScrubber from '../components/VideoScrubber';
import CommandPreview from '../components/CommandPreview';
import ProgressPanel from '../components/ProgressPanel';
import { api } from '../api';
import { useTask } from '../hooks/useTask';
import { useMediaSource } from '../hooks/useMediaSource';
import { useCommandPreview } from '../hooks/useCommandPreview';
import { baseFields } from '../hooks/baseFields';

export default function TrimTab() {
  const { file, info, loadingInfo, probeError, outPath, setOutPath, previewURL, previewNote, preparing, load } =
    useMediaSource('trim', { withPreview: true });

  const [accurate, setAccurate] = useState(false);
  const [range, setRange] = useState({ start: 0, end: 0 });

  // load 是异步的：await load(f) 之后读 info 拿到的是闭包里的旧值（React state
  // 不会同步更新，Vue ref 会）。所以用文件指纹（path + duration + size）守卫的
  // useEffect，等 info 到位后给新文件初始化一次 range，不跟用户后续的手动调整打架。
  const initKey = useRef('');
  useEffect(() => {
    if (!file || !info) return;
    const key = `${file.path}::${info.duration ?? ''}::${info.size ?? ''}`;
    if (initKey.current === key) return;
    initKey.current = key;
    setRange({ start: 0, end: info.duration || 0 });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [file, info]);

  const segLen = Math.max(0, (range.end || 0) - (range.start || 0));

  function buildSpec() {
    if (!file || !outPath || !info) return null;
    if (!range.end) return null;
    return {
      kind: 'trim',
      output: outPath,
      ...baseFields(file, info),
      trim: { start: Number(range.start), end: Number(range.end), accurate: accurate },
    };
  }

  const { cmd } = useCommandPreview(buildSpec, [file, outPath, accurate, range, info]);
  const { running, progress, stage, logs, result, start, cancel } = useTask();

  async function run() {
    const spec = buildSpec();
    if (!spec) return;
    try {
      await start(spec);
    } catch (e: any) {
      window.alert('无法启动任务：' + (e?.message || e));
    }
  }

  async function pickOutput() {
    const ext = file?.name?.match(/\.[^.]+$/)?.[0] || '.mp4';
    const name = (file?.name || 'output').replace(/\.[^.]+$/, '') + '_trimmed' + ext;
    const p = await api.pickSaveFile(name, `*${ext}`);
    if (p) setOutPath(p);
  }

  const modeHint = accurate
    ? '精确模式：逐帧定位，起点终点都准。速度取决于片段长度'
    : '快速模式：不重新编码，秒级完成。但起止点会吸附到最近的关键帧，可能差 1~2 秒';

  return (
    <>
      <div className="card">
        <h2>源文件</h2>
        <FilePicker value={file} onChange={load} label="选择要截取的视频，也可以直接拖进来" />
        {file && (
          <div style={{ marginTop: 12 }}>
            <MediaInfoCard info={info} loading={loadingInfo} />
            {preparing ? (
              <div className="banner info" style={{ marginTop: 10 }}>
                正在准备预览…
              </div>
            ) : (
              previewNote && (
                <div className="banner info" style={{ marginTop: 10 }}>
                  {previewNote}
                </div>
              )
            )}
            {probeError && (
              <div className="banner warn" style={{ marginTop: 10 }}>
                {probeError}
              </div>
            )}
          </div>
        )}
      </div>

      {file && previewURL && (
        <div className="card">
          <h2>
            选择片段 <span className="hint">拖动两端手柄调整范围，点上任意位置可跳到该处预览</span>
          </h2>
          <VideoScrubber
            src={previewURL}
            duration={info?.duration || 0}
            mode="range"
            value={range}
            onChange={(v) => setRange({ start: v.start, end: v.end })}
          />
        </div>
      )}

      {file && (
        <div className="card">
          <h2>截取方式</h2>
          <div className="modes">
            <button className={`mode${!accurate ? ' on' : ''}`} onClick={() => setAccurate(false)}>
              <b>快速</b>
              <span>不重编码，秒级完成</span>
            </button>
            <button className={`mode${accurate ? ' on' : ''}`} onClick={() => setAccurate(true)}>
              <b>精确</b>
              <span>逐帧精确，需要重新编码</span>
            </button>
          </div>
          <div className="banner info" style={{ marginTop: 12, marginBottom: 0 }}>
            {modeHint}
          </div>
        </div>
      )}

      {file && (
        <div className="card">
          <h2>输出</h2>
          <div className="field">
            <label>输出路径</label>
            <div className="row">
              <Input value={outPath} onChange={(e) => setOutPath(e.target.value)} className="mono" style={{ flex: 1 }} />
              <button onClick={pickOutput}>浏览…</button>
            </div>
          </div>

          <CommandPreview steps={cmd.steps} err={cmd.err} />

          <div className="row" style={{ marginTop: 14 }}>
            <button className="primary" disabled={running || !outPath || segLen <= 0} onClick={run}>
              {running ? '处理中…' : `开始截取（${segLen.toFixed(1)} 秒）`}
            </button>
          </div>
        </div>
      )}

      <ProgressPanel
        running={running}
        progress={progress}
        stage={stage}
        logs={logs}
        result={result}
        onCancel={cancel}
        onOpenFile={api.openPath}
        onOpenDir={api.openDirectory}
      />
    </>
  );
}
